### ISSUE TITLE
Add option for darker highlight on Visual selection

### ISSUE THREAD

**Issue by mizlan** [cideM/yui#18]
Hi! Really enjoying the theme! One thing I dislike is the white visual selection, I would prefer an option for a shade that is lighter than the text but darker than the background color.

**Comment by cideM** [comment]
I don't know why I didn't see this issue and PR, sorry about that! I'll take a look

**Comment by cideM** [comment]
For what it's worth I've decided that now is a good time to think about an actual version 1 of this scheme. I never advertised it because this theme was literally me needing a simple light colorscheme and so I created one. But the color palette could be  bit more refined, it could support more third party plugins, and I'd like to remove the colortemplate dependency.

I've pushed a `v2` branch (the name is wrong, I will at some point rename it to `v1` or something) where I've implemented a dark visual selection since I actually ended up liking it more than the bright white.

I'll make a proper issue about the v1 thing and add some thoughts and what I'm planning on doing exactly.

**Comment by mizlan** [comment]
Sounds good!

> I'd like to remove the colortemplate dependency.

I think it might actually be better to keep it, because it might be easier to maintain. But it's up to you.

**Comment by mizlan** [comment]
Also just as a suggestion, the highlight groups `PmenuSel`, `WildMenu`, `CursorLine`, `CursorLineNr` are also using white background, in case you wanted to change those as well.

**Comment by cideM** [comment]
Took care of these in the most recent commit which I'll push in a few min
