### ISSUE TITLE
Fold background

### ISSUE THREAD

**Issue by eemed** [cideM/yui#5]
I feel the folds are too invisible, I know this is really just a suggestion. I would propose a slightly lighter or darker background for folds to differentiate them better. The left one is my experiment and right one is current.
![diff](https://user-images.githubusercontent.com/30186515/85420060-6c409c80-b57b-11ea-8f17-678495d40caa.png)

**Comment by cideM** [comment]
Would increasing the contrast for the folds also be an option, instead of adding a background? I'm personally not a fan of background on folds. I really comes down to personal preference of course. Adding an option so users can choose between two folded backgrounds would also be an... an option. I'll try to see if I have time to create a branch for this today

**Comment by eemed** [comment]
Increasing contrast should also be fine.

**Comment by cideM** [comment]
Give the `folds` branch a try

![Screenshot from 2020-06-28 10-07-45](https://user-images.githubusercontent.com/4246921/85942182-fe53f680-b927-11ea-82cb-c7f922a30dcd.png)
![Screenshot from 2020-06-28 10-11-01](https://user-images.githubusercontent.com/4246921/85942183-feec8d00-b927-11ea-97ef-0d554f59edf5.png)

**Comment by eemed** [comment]
Background looks great. I think the foreground should be slightly lighter than normal text.

**Comment by cideM** [comment]
Pushed another little adjustment
![Screenshot from 2020-06-28 10-40-59](https://user-images.githubusercontent.com/4246921/85942788-dd8da000-b92b-11ea-95b3-0de1d22cc23b.png)

**Comment by eemed** [comment]
That looks good. thanks

**Comment by cideM** [comment]
Closed by #7
